# Generated by Django 4.2.2 on 2023-06-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the publisher.', max_length=50)),
                ('website', models.URLField(help_text='Website of the publisher.')),
                ('email', models.EmailField(help_text='Address email of the publisher', max_length=254)),
            ],
        ),
    ]
